### ISSUE TITLE
Document Sol·licitud d'emissió de factura

### ISSUE THREAD

**Issue by jvilaplana** [IRBLleida/BethaX#77]
En la pantalla de tancament, permetre descarregar un arxiu Word i adjuntar-lo emplenat.

**Comment by jvilaplana** [comment]
Camp opcional.

**Comment by pbalaguer19** [comment]
Solament cal descarregar-lo. No fa falta un camp per pujar-lo

**Comment by jvilaplana** [comment]
Fet.
